### ISSUE TITLE
Update OAS spec to be compliant

### ISSUE THREAD

**Issue by hammar** [RealEstateCore/rec#70]
Colons are disallowed in the component names. Concatenate qName into camel case instead?

**Comment by hammar** [comment]
OWL2OAS generator is updated to be compliant, just need to build new YAML file in 3.2 release process.

**Comment by hammar** [comment]
Also need to ensure OWL2OAS respects o2o:listProperty annotations

**Comment by hammar** [comment]
This ought to be generated for properties w/ `owo:listProperty` set:

```
{
  "@context": {
    "@base": "http://example.com",
    "label": "http://www.w3.org/2000/01/rdf-schema#label",
    "analytics": "https://w3id.org/rec/analytics/",
    "core": "https://w3id.org/rec/core/"
  },
  "@id": "GUID-GOES-HERE",
  "@type": "analytics:DataSeries",
  "label": "This is a data series!",
  "analytics:seriesMembers": {
    "@list": [ 
      {
      "@id": "OBS1",
      "@type": "core:Observation"
      },
      {
      "@id": "OBS2",
      "@type": "core:Observation"
      }
    ]
  },
  "analytics:generatedBy": [
    {
      "@id": "ADDITION_PROCESS",
      "@type": "analytics:AnalysisProcess"
    }
  ]
}
```

**Comment by hammar** [comment]
OAS YAML:
```
    analytics_DataSeries:
      type: object
      required:
      - '@context'
      properties:
        '@id':
          type: string
        '@type':
          type: string
          default: analytics:DataSeries
        label:
          type: string
        analytics:seriesMembers:
          type: object
          required: 
          - '@list'
          properties:
            '@list':
              type: array
              items:
                type: object
                required:
                - '@id'
                properties:
                  '@id':
                    type: string
                  '@type':
                    type: string
                    default: core:Observation
              minItems: 1
```
